sudo: false 
dist: trusty

script:

- ./script.sh hello world >> output.txt
- OUTPUT=$(cat output.txt)
- echo $OUTPUT
- travis_wait ./script.sh hello wait

after_script:

- WAIT=$(cat wait.txt)
- echo $wait