sudo: false 
dist: trusty

script:

- ./script.sh hello world >> output.txt
- OUTPUT=$(cat output.txt)
- echo $OUTPUT
- travis_wait 30 ./script.sh hello wait >> wait.txt

after_script:

- WAIT=$(cat wait.txt)
- echo $wait